// <auto-generated />
using System;
using HelloWorldAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloWorldAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250705203752_UpdateOrderTable")]
    partial class UpdateOrderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelloWorldAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Price")
                        .HasColumnType("real");

                    b.Property<int?>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2025, 5, 27, 4, 13, 7, 141, DateTimeKind.Utc).AddTicks(2842),
                            Name = "Order 1",
                            Number = "Order-1",
                            Price = 20.5f,
                            Qty = 2
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2025, 5, 27, 4, 13, 7, 141, DateTimeKind.Utc).AddTicks(2842),
                            Name = "Order 2",
                            Number = "Order-2",
                            Price = 15f,
                            Qty = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2025, 5, 27, 4, 13, 7, 141, DateTimeKind.Utc).AddTicks(2842),
                            Name = "Order 3",
                            Number = "Order-3",
                            Price = 50f,
                            Qty = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
